### PR TITLE
Cleaning...

### PR DESCRIPTION
**Pull request by sballu**
Hi, I removed some duplicated typedef and declaration.

Can help with older version of GCC

### CODE REVIEW

**Comment by a1batross** [comment]
This typedefs should not be removed. 
This is a shared headers between four libs(engine, client, server and menu) so any changes here will possibly break the compability.

**Comment by sballu** [comment]
I tried under linux and had no problem.
And we have less warning when using -pedantic option.
And with old version of gcc, redefinition of typedef cause an error.
(For example on my old Mac, where I have gcc 4.2.1)

**Comment by a1batross** [comment]
I compared this com_model.h file with HLSDK's header. 
I don't have any notes here now. :)

**Comment by sballu** [comment]
What do you mean ?

If you want I can close this pull request and create a new one with only the changes in gl_export.h

**Comment by nekonomicon** [comment]
I tried build with gcc 4.2.1 on FreeBSD 9.3-RELEASE:

Scanning dependencies of target xashmenu
[  1%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_playersetup.cpp.o
[  2%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_controls.cpp.o
[  3%] Building CXX object mainui/CMakeFiles/xashmenu.dir/udll_int.cpp.o
[  3%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_saveload.cpp.o
[  4%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_credits.cpp.o
Scanning dependencies of target xash
[  4%] Building CXX object engine/CMakeFiles/xash.dir/platform/android/android-gameif.cpp.o
[  5%] Building CXX object engine/CMakeFiles/xash.dir/platform/android/dlsym-weak.cpp.o
[  6%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_customgame.cpp.o
[  7%] Building CXX object engine/CMakeFiles/xash.dir/platform/android/android-touchif.cpp.o
[  7%] Building C object engine/CMakeFiles/xash.dir/server/sv_custom.c.o
In file included from /usr/ports/games/xash3d/work/xash3d-90b8efd/engine/common/common.h:95,
                 from /usr/ports/games/xash3d/work/xash3d-90b8efd/engine/server/sv_custom.c:16:
/usr/ports/games/xash3d/work/xash3d-90b8efd/engine/common/system.h:41: error: redefinition of typedef 'byte'
/usr/ports/games/xash3d/work/xash3d-90b8efd/engine/../common/port.h:82: error: previous declaration of 'byte' was here
In file included from /usr/ports/games/xash3d/work/xash3d-90b8efd/engine/common/system.h:59,
                 from /usr/ports/games/xash3d/work/xash3d-90b8efd/engine/common/common.h:95,
                 from /usr/ports/games/xash3d/work/xash3d-90b8efd/engine/server/sv_custom.c:16:
/usr/ports/games/xash3d/work/xash3d-90b8efd/engine/../common/const.h:733: error: redefinition of typedef 'byte'
/usr/ports/games/xash3d/work/xash3d-90b8efd/engine/common/system.h:41: error: previous declaration of 'byte' was here
In file included from /usr/ports/games/xash3d/work/xash3d-90b8efd/engine/common/common.h:97,
                 from /usr/ports/games/xash3d/work/xash3d-90b8efd/engine/server/sv_custom.c:16:
/usr/ports/games/xash3d/work/xash3d-90b8efd/engine/../common/com_model.h:21: error: redefinition of typedef 'vec2_t'
/usr/ports/games/xash3d/work/xash3d-90b8efd/engine/common/system.h:44: error: previous declaration of 'vec2_t' was here
/usr/ports/games/xash3d/work/xash3d-90b8efd/engine/../common/com_model.h:22: error: redefinition of typedef 'vec4_t'
/usr/ports/games/xash3d/work/xash3d-90b8efd/engine/common/system.h:46: error: previous declaration of 'vec4_t' was here
*** [engine/CMakeFiles/xash.dir/server/sv_custom.c.o] Error code 1
1 error
*** [engine/CMakeFiles/xash.dir/all] Error code 2
[  7%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_vidoptions.cpp.o
[  8%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_main.cpp.o
[  9%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_video.cpp.o
[ 10%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_multiplayer.cpp.o
[ 10%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_vidmodes.cpp.o
[ 11%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_gameoptions.cpp.o
[ 12%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_strings.cpp.o
[ 12%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_newgame.cpp.o
[ 13%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_savegame.cpp.o
[ 14%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_loadgame.cpp.o
[ 14%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_configuration.cpp.o
[ 15%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_advcontrols.cpp.o
[ 16%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_btns.cpp.o
[ 17%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_audio.cpp.o
[ 17%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_internetgames.cpp.o
[ 18%] Building CXX object mainui/CMakeFiles/xashmenu.dir/ui_title_anim.cpp.o
[ 19%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_langame.cpp.o
[ 19%] Building CXX object mainui/CMakeFiles/xashmenu.dir/utils.cpp.o
[ 20%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_creategame.cpp.o
[ 21%] Building CXX object mainui/CMakeFiles/xashmenu.dir/basemenu.cpp.o
[ 22%] Linking CXX shared library libxashmenu.so
[ 22%] Built target xashmenu
1 error
*** [all] Error code 2
1 error
===> Compilation failed unexpectedly.

**Comment by sballu** [comment]
With gcc 4.2.1, you need more changes than the ones I made, I thought theses changes could be a first step :p

**Comment by a1batross** [comment]
No, I mean that changing the common header will not affect anything. BecauseHLSDK don't have these typedefs.

**Comment by sballu** [comment]
Ok nice then.
